### PR TITLE
fixed the code causing deployment failure in vercel

### PR DESCRIPTION
**Pull request by SriramSonaganti**

### CODE REVIEW

**Review by ZiaCodes — APPROVED** [review]
@SriramSonaganti #1

**Comment by ZiaCodes** [comment]
> _ No description provided. _

Can you upstream again ?? since it has so many conflict

**Comment by SriramSonaganti** [comment]
> > _ No description provided. _
> 
> Can you upstream again ?? since it has so many conflict

yeah sure will do!

**Review by ZiaCodes — APPROVED** [review]
@SriramSonaganti #1

**Pull request merged**
