### PR TITLE
Intergrate the register service

### PR DESCRIPTION
**Pull request by harshit-070**

### CODE REVIEW

**Comment by ZiaCodes** [comment]
> _No description provided._

I think there is some problem , let me review it again

**Comment by harshit-070** [comment]
Hi, may I know the problem?

**Comment by ZiaCodes** [comment]
> Hi, may I know the problem?

there is a problem with the deployment..

**Review by ZiaCodes — APPROVED** [review]
#24 @Aniket-508 
Okay done

**Pull request merged**
